# Generated by Django 6.0.3 on 2026-03-31 09:38

from django.db import migrations, models


# MIGRATION D'AJOUT DE CHAMP ARCHIVAGE
class Migration(migrations.Migration):

    # DÉPENDANCES DE LA MIGRATION
    dependencies = [
        ('tickets', '0001_initial'),  # Dépend de la migration initiale
    ]

    # OPÉRATIONS À EXÉCUTER
    operations = [
        # AJOUT D'UN CHAMP BOOLÉEN
        migrations.AddField(
            model_name='ticket',           # Modèle cible
            name='est_archive',            # Nom du champ
            field=models.BooleanField(     # Type : booléen
                default=False              # Valeur par défaut : non archivé
            ),
        ),
    ]